### ISSUE TITLE
Better chapel-mode

### ISSUE THREAD

**Issue by damon-kwok** [russel/Emacs-Chapel-Mode#3]
@russel I saw that the `chapel-mode` has not been maintained for a long time. Would you like to redirect?
If you agree, you need to submit a PR to MELPA. 

## MELPA
https://github.com/melpa/melpa/blob/master/recipes/chapel-mode

## original
```elisp
(chapel-mode :fetcher github :repo "russel/Emacs-Chapel-Mode")
```
## changed:
```elisp
(chapel-mode
  :fetcher github
  :repo "damon-kwok/chapel-mode"
  :files (:defaults "etc"))
```

## See:
https://github.com/damon-kwok/chapel-mode

**Comment by damon-kwok** [comment]
@russel If you agree with my proposal, I can submit a PR to `MELPA`.

**Comment by russel** [comment]
@damon-kwok I have not been using Chapel for a while now, hence the apparent (well real actually) lack of maintenance of this Emacs mode. If you are willing and able to take over as mainline for the mode, I would be very happy. Do you want me to to submit the change as originally suggested, or is it better if you submit a change?

**Comment by damon-kwok** [comment]
@russel Thanks. I cannot modify the `recipes/chapel-mode` on the `MELPA`, because you are the original contributor, I must get your permission or submit a PR by you.

**Comment by russel** [comment]
@damon-kwok Does me setting the repo from me to you pass the permission to update the recipe from me to you?

**Comment by damon-kwok** [comment]
Just update recipes/chapel-mode.

**Comment by damon-kwok** [comment]
@russel Like this:
https://github.com/melpa/melpa/pull/6312

**Comment by russel** [comment]
I have submitted a merge request https://github.com/melpa/melpa/pull/7066

**Comment by damon-kwok** [comment]
@russel Thanks~

**Comment by russel** [comment]
When the merge request goes through, I will retire this repository and add a pointer to your repository.

**Comment by russel** [comment]
MELPA has actioned the change, so I believe it is over to you @damon-kwok

**Comment by damon-kwok** [comment]
@russel Big thanks~
